version: '3.8'


services:

  db:
    image: mariadb:10
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: adminpass
      MYSQL_USER: "angelo"
      MYSQL_PASSWORD: "angelopss"
      MYSQL_DATABASE: nevrologiya
    ports:
      - "3306:3306"
    volumes:
      - mariadbData:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

#  python:
#    build: .
#    container_name: app-python
#    restart: always
#
#    volumes:
#      - ./:/usr/src/app/
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    environment:
#      MYSQL_DATABASE: nevrologiya
#      MYSQL_USER: angelo
#      MYSQL_PASSWORD: angelopss

volumes:
  mariadbData:
