# Generated by Django 4.2 on 2023-04-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("status", models.BooleanField(default=True, verbose_name="Yoshi")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                        verbose_name="Jinsi",
                    ),
                ),
                ("symptom", models.TextField()),
                ("event", models.TextField()),
            ],
            options={
                "db_table": "patient",
            },
        ),
    ]
