# Generated by Django 4.2 on 2023-04-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="Yoshi")),
                (
                    "gender",
                    models.CharField(
                        choices=[("erkak", "Erkak"), ("ayol", "Ayol")],
                        max_length=10,
                        verbose_name="Jinsi",
                    ),
                ),
                ("symptom", models.CharField(max_length=50, verbose_name="Simtomlar")),
                ("event", models.TextField(max_length=50, verbose_name="Xulosa")),
            ],
            options={
                "db_table": "patient",
            },
        ),
    ]
