# Generated by Django 4.2 on 2023-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("age", "gender", "symptom", "event"),
                name="uk_patient_age_gender_symtom_event",
            ),
        ),
    ]
